### ISSUE TITLE
Failing GitHub quality control

### ISSUE THREAD

**Issue by JCGiron** [insect-morphology/colao#25]
We have GitHub quality control issues making the onltology be listed as "failing" and I'm not sure what the problem is.

![image](https://github.com/insect-morphology/colao/assets/37313282/9fbbc28d-22c6-40ce-b7d2-f4044048951a)

We get `UNKNOWN ARG ERROR unknown command or option: --base-iri`

![image](https://github.com/insect-morphology/colao/assets/37313282/a9b95848-0b59-44c2-b891-9b293041c5c2)

And later `make: *** [reports/colao-edit.owl-obo-report.tsv] Error 1`
![image](https://github.com/insect-morphology/colao/assets/37313282/8732fafb-bf9e-4820-8622-e3bc4b12046d)

It looks like something is wrong with one of our make files?
@matentzn

**Comment by matentzn** [comment]
You have to edit this file:

.github/workflows/qc.yml

And change the ODK it is using to 1.4.3 (line 22 in that file).

**Comment by JCGiron** [comment]
I can't find a workflows folder within the GitHub folder in my computer. Should that be within the COLAO repository somewhere?

**Comment by matentzn** [comment]
On windows the directory will be hidden. It's there. Just change on GitHub using the edit button

**Comment by JCGiron** [comment]
On a mac, this is what my GiHub folder has:
![image](https://github.com/insect-morphology/colao/assets/37313282/3c968bb1-78a9-4c1f-9792-9f42a282ede2)

**Comment by matentzn** [comment]
It's in colao/.GitHub folder (sorry last message) - I recommend to use GitHub. Cc @anitacaron in case you can't find it

**Comment by JCGiron** [comment]
Found it!
![image](https://github.com/insect-morphology/colao/assets/37313282/ac63ca67-9621-4e7f-859b-8551214628e7)

Will try that after "we" figure out the imports issue.

Should I try a release after I update the qc.yml file to the latest ODK version to see if the imports issue gets fixed?

**Comment by matentzn** [comment]
This will only help with QC, not the release unfortunately.. I won't be able to help until Monday now, but please reach out in the ODK channel, point to the OdK issue and ask for help. Damien and Anita are usually very helpful.

**Comment by JCGiron** [comment]
GitHub quality control issues cleared.
